<a href="https://colab.research.google.com/github/Jaswithagadde/GenAI_Workshop/blob/main/Examples_WithoutPipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. Sentiment Analysis**

In [ ]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch

In [ ]:
model = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased-finetuned-sst-2-english"
)

tokenizer = AutoTokenizer.from_pretrained(
    "distilbert-base-uncased-finetuned-sst-2-english"
)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:124: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

In [ ]:
text = input("Enter text: ")

Enter text: i,m very excited to see this movie?


In [ ]:
inputs = tokenizer(text, return_tensors="pt")

print(inputs)

{'input_ids': tensor([[ 101, 1045, 1010, 1049, 2200, 7568, 2000, 2156, 2023, 3185, 1029,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}


In [ ]:
outputs = model(**inputs)
print(outputs.logits)

tensor([[-3.9729,  4.2959]], grad_fn=<AddmmBackward0>)


In [ ]:
predictions = torch.nn.functional.softmax(outputs.logits, dim=-1)
print(predictions)

tensor([[2.5632e-04, 9.9974e-01]], grad_fn=<SoftmaxBackward0>)


In [ ]:
prediction_class_id = outputs.logits.argmax().item()

print(prediction_class_id)

1


In [ ]:
print("Sentiment:", model.config.id2label[prediction_class_id])

Sentiment: POSITIVE


**2. Summarization**

In [2]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

In [3]:
model = AutoModelForSeq2SeqLM.from_pretrained(
    "facebook/bart-large-cnn"
)

tokenizer = AutoTokenizer.from_pretrained(
    "facebook/bart-large-cnn"
)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:124: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/1.58k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

[transformers] Please make sure the generation config includes `forced_bos_token_id=0`. 


Loading weights:   0%|          | 0/511 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

In [4]:
text = input("Enter article: ")

Enter article: Features of AIML data-driven: The user's queries are predefined as conditions and mapped with particular actions for generating automated responses for users. Rule-based Scripting language: If the conditions get satisfied, it performs an action based on the rule; if the condition does not get satisfied, then it stops. XML-based: AIML is easy to learn for programmers who know HTML or XML because it has a similar syntax to HTML and XML. It enables integration with XML editors using XML syntax. Flexibility: Customized tags and functions can be created for efficient code writing in development. Random Actions: Based on a single condition, multiple actions can be defined. AIML Tags and their syntax There are multiple elements and tags in AIML and we are going to see some basic elements with their syntax.  1. <aiml>: Inside this tag, all tags are defined. It constructs the starting and ending of an AIML document.  <aiml> <!-- all the tags that contain conditions and actions-->

In [5]:
inputs = tokenizer(text, return_tensors="pt")

In [6]:
print(inputs)

{'input_ids': tensor([[    0, 48192,     9,    83,  3755,   574,   414,    12,  9756,    35,
            20,  3018,    18, 22680,    32, 12574, 38716,    25,  1274,     8,
         33493,    19,  1989,  2163,    13, 10846, 11554,  8823,    13,  1434,
             4, 16654,    12,   805, 32175,   154,  2777,    35,   318,     5,
          1274,   120, 10028,     6,    24, 14023,    41,   814,   716,    15,
             5,  2178,   131,   114,     5,  1881,   473,    45,   120, 10028,
             6,   172,    24,  6897,     4, 46917,    12,   805,    35,    83,
          3755,   574,    16,  1365,     7,  1532,    13, 37638,    54,   216,
         23669,    50, 46917,   142,    24,    34,    10,  1122, 45362,     7,
         23669,     8, 46917,     4,    85,  9849,  7465,    19, 46917, 15136,
           634, 46917, 45362,     4, 19948, 12203,    35, 16583,  1538, 19445,
             8,  8047,    64,    28,  1412,    13,  5693,  3260,  2410,    11,
           709,     4, 34638, 41443,  

In [7]:
summary = model.generate(
    inputs["input_ids"],
    max_length=50
)

print(summary)

/usr/local/lib/python3.12/dist-packages/transformers/generation/utils.py:1640: UserWarning: Unfeasible length constraints: `min_length` (56) is larger than the maximum possible length (50). Generation will stop at the defined maximum length. You should decrease the minimum length and/or increase the maximum length.
  warnings.warn(


tensor([[    2,     0, 48192,     9,    83,  3755,   574,   414,    12,  9756,
            35,    20,  3018,    18, 22680,    32, 12574, 38716,    25,  1274,
             8, 33493,    19,  1989,  2163,    13, 10846, 11554,  8823,    13,
          1434,     4, 16654,    12,   805, 32175,   154,  2777,    35,   318,
             5,  1274,   120, 10028,     6,    24, 14023,    41,   814,     2]])


In [8]:
print(tokenizer.decode(
    summary[0],
    skip_special_tokens=True
))

Features of AIML data-driven: The user's queries are predefined as conditions and mapped with particular actions for generating automated responses for users. Rule-based Scripting language: If the conditions get satisfied, it performs an action


**3. Translation**

In [16]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

In [28]:
model = AutoModelForSeq2SeqLM.from_pretrained(
    "Helsinki-NLP/opus-mt-en-fr"#english to french

)

tokenizer = AutoTokenizer.from_pretrained(
    "Helsinki-NLP/opus-mt-en-fr"#english to french

)


Loading weights:   0%|          | 0/258 [00:00<?, ?it/s]

In [29]:
text = input("Enter English text: ")

Enter English text: what is your name ?


In [30]:
inputs = tokenizer(text, return_tensors="pt")

print(inputs)

{'input_ids': tensor([[ 270,   32,  117, 1129,   99,    0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1]])}


In [31]:

translation = model.generate(**inputs)

print(translation)

tensor([[59513,  4290,    43,   193,   689,    99,     0]])


In [32]:
print(tokenizer.decode(
    translation[0],
    skip_special_tokens=True
))

Quel est votre nom ?


**4. Text Generation**

In [49]:
from transformers import AutoTokenizer, AutoModelForCausalLM

In [50]:
tokenizer = AutoTokenizer.from_pretrained(
    "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
)
model = AutoModelForCausalLM.from_pretrained(
     "TinyLlama/TinyLlama-1.1B-Chat-v1.0")

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

In [ ]:
user_prompt = input("Enter a prompt: ")

In [36]:
inputs = tokenizer(user_prompt, return_tensors="pt")

print(inputs)

{'input_ids': tensor([[  1, 825, 338, 596]]), 'attention_mask': tensor([[1, 1, 1, 1]])}


In [37]:
output = model.generate(
    **inputs,
    max_new_tokens=50
)

print(output)

[transformers] Both `max_new_tokens` (=50) and `max_length`(=2048) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)


tensor([[    1,   825,   338,   596, 25448,  1134,   310,  4696, 29973,     2]])


In [38]:
response = tokenizer.decode(
    output[0],
    skip_special_tokens=True
)

print("\nGenerated Response:")
print(response)


Generated Response:
what is your favorite type of music?


5. Question Answering

In [1]:
from transformers import AutoTokenizer,AutoModelForQuestionAnswering


In [2]:
tokenizer = AutoTokenizer.from_pretrained(
    "bert-large-uncased-whole-word-masking-finetuned-squad"
)
model = AutoModelForQuestionAnswering.from_pretrained(
     "bert-large-uncased-whole-word-masking-finetuned-squad")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:124: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/443 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.34G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

[transformers] BertForQuestionAnswering LOAD REPORT from: bert-large-uncased-whole-word-masking-finetuned-squad
Key                      | Status     |  | 
-------------------------+------------+--+-
bert.pooler.dense.bias   | UNEXPECTED |  | 
bert.pooler.dense.weight | UNEXPECTED |  | 

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.


In [13]:
context = """AIML (Artificial Intelligence Markup Language) is an XML dialect for creating natural language software agents, or chat-bots. AIML was developed by Richard Wallace and the global free software community between 1995 and 2000. It forms the basis for A.L.I.C.E. (Artificial Linguistic Internet Computer Entity), a natural language processing chatbot. AIML provides a simple way to define patterns that map user inputs to bot responses. For example, a pattern could be 'WHAT IS YOUR NAME' and the corresponding template would be 'My name is A.L.I.C.E.'. It is widely used in conversational AI applications due to its simplicity and flexibility."""
question = input("Enter the question: ")

Enter the question: what is aiml


In [14]:
import torch

inputs = tokenizer(
    question,
    context,
    return_tensors="pt"
)

with torch.no_grad():
    outputs = model(**inputs)

start_index = torch.argmax(outputs.start_logits)
end_index = torch.argmax(outputs.end_logits) + 1

answer = tokenizer.decode(
    inputs["input_ids"][0][start_index:end_index]
)

print("\nAnswer:")
print(answer)


Answer:
an xml dialect for creating natural language software agents, or chat - bots
